### ISSUE TITLE
Finish burschi

### ISSUE THREAD

**Issue by Eik-S** [Eik-S/burschi#3]
## Crawlers:
- [ ] burschis@wiki
- [ ] crawl their websites ( collect all links going out of their website)
- [ ] create dictionary, each burschi needs a unique identifier as a key and the value is a list of all the links

## Data Processing:
- [ ] check connections from the website of one burschenschaft to another ( subdomains & routes of the links can be cut before)
- [ ] create dict having a a key nodes and a key links with all the nodes and links
Nodes are created for each burschi
Links are created if one burschisite links to another

### Format:

```python
burschis = {
    "nodes": [
        { "id":"wirSindNurTraditionell"},
        { "id":"eyDerSagtNaziZuUns"}
    ],
    "links": [
        { 
            "source":"wirSindNurTraditionell",
            "target":"eyDerSagtNaziZuUns",
            "value":"5" #amount of links
        },{ 
            "source":"eyDerSagtNaziZuUns",
            "target":"wirSindNurTraditionell",
            "value":"3" #amount of links
        },
    ]
}
```

## d3js

In d3 this object can directly be used for visualizing a network.
As soon as thats finished, we could discuss the next steps like:
 - display some basic information about this burschi in a little window
 - highlight neighbors on hover
 - ...
